version: "3.7"

services:
  orderer.product.com:
    container_name: orderer.product.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LISTENPORT=7050

    volumes:
      # - ./:/etc/hyperledger/configtx
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/product.com/orderers/orderer.product.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/product.com/orderers/orderer.Product.com/tls/:/var/hyperledger/orderer/tls
      - orderer.product.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.city1.product.com:
    container_name: peer0.city1.product.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.city1.product.com
      - CORE_PEER_ADDRESS=peer0.city1.product.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.city1.product.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.city1.product.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.city1.product.com:7051
      - CORE_PEER_LOCALMSPID=city1MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/city1.product.com/peers/peer0.city1.product.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/city1.product.com/peers/peer0.city1.product.com/tls:/etc/hyperledger/fabric/tls
      - peer0.city1.product.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.city1.product.com:
    container_name: peer1.city1.product.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.city1.product.com
      - CORE_PEER_ADDRESS=peer1.city1.product.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.city1.product.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.city1.product.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.city1.product.com:8051
      - CORE_PEER_LOCALMSPID=city1MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/city1.product.com/peers/peer1.city1.product.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/city1.product.com/peers/peer1.city1.product.com/tls:/etc/hyperledger/fabric/tls
      - peer1.city1.product.com:/var/hyperledger/production
    ports:
      - 8051:8051

  peer0.city2.product.com:
    container_name: peer0.city2.product.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.city2.product.com
      - CORE_PEER_ADDRESS=peer0.city2.product.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.city2.product.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.city2.product.com:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.city2.product.com:9051
      - CORE_PEER_LOCALMSPID=city2MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/city2.product.com/peers/peer0.city2.product.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/city2.product.com/peers/peer0.city2.product.com/tls:/etc/hyperledger/fabric/tls
      - peer0.city2.product.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.city2.product.com:
    container_name: peer1.city2.product.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.city2.product.com
      - CORE_PEER_ADDRESS=peer1.city2.product.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.city2.product.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.city2.product.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.city2.product.com:10051
      - CORE_PEER_LOCALMSPID=city2MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/city2.product.com/peers/peer1.city2.product.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/city2.product.com/peers/peer1.city2.product.com/tls:/etc/hyperledger/fabric/tls
      - peer1.city2.product.com:/var/hyperledger/production
    ports:
      - 10051:10051

  peer0.city3.product.com:
    container_name: peer0.city3.product.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.city3.product.com
      - CORE_PEER_ADDRESS=peer0.city3.product.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.city3.product.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.city3.product.com:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.city3.product.com:11051
      - CORE_PEER_LOCALMSPID=city3MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/city3.product.com/peers/peer0.city3.product.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/city3.product.com/peers/peer0.city3.product.com/tls:/etc/hyperledger/fabric/tls
      - peer0.city3.product.com:/var/hyperledger/production
    ports:
      - 11051:11051

  peer1.city3.product.com:
    container_name: peer1.city3.product.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.city3.product.com
      - CORE_PEER_ADDRESS=peer1.city3.product.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.city3.product.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.city3.product.com:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.city3.product.com:12051
      - CORE_PEER_LOCALMSPID=city3MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/city3.product.com/peers/peer1.city3.product.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/city3.product.com/peers/peer1.city3.product.com/tls:/etc/hyperledger/fabric/tls
      - peer1.city3.product.com:/var/hyperledger/production
    ports:
      - 12051:12051
