version: "2"

networks:
  network:

services:
  ca.city1.product.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    platform: linux/x86_64
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-city1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    #       - FABRIC_CA_SERVER_TLS_ENABLED=true
    # - FABRIC_CA_SERVER_TLS_CERTFILE=<location to certificate file>
    # - FABRIC_CA_SERVER_TLS_KEYFILE=<location to key file>
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./organizations/fabric-ca/city1:/etc/hyperledger/fabric-ca-server
    networks:
      - network
    container_name: ca.city1.product.com

  ca.city2.product.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    platform: linux/x86_64
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-city2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./organizations/fabric-ca/city2:/etc/hyperledger/fabric-ca-server
    networks:
      - network
    container_name: ca.city2.product.com

  ca.city3.product.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    platform: linux/x86_64
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-city3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=10054
    ports:
      - "10054:10054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./organizations/fabric-ca/city3:/etc/hyperledger/fabric-ca-server
    networks:
      - network
    container_name: ca.city3.product.com

  ca.orderer.product.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    platform: linux/x86_64
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
    networks:
      - network
    container_name: ca.orderer.product.com
